# Generated by Django 5.0.7 on 2024-10-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AlterField(
            model_name='class',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='school.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='school.studentprofile'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='school.class'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='school.class'),
        ),
    ]
